// Code generated by gencontrollers; DO NOT EDIT.
package ioc

import (
    "gin_boot/internal/controller"
    "github.com/google/wire"
)

// ControllerSet 是所有 Controller 构造函数的集合
var ControllerSet = wire.NewSet(
    controller.NewCaptchaController,
    controller.NewUserController,
)
