// Code generated by gencontrollers; DO NOT EDIT.
package ioc

import (
	"gin_boot/internal/service"
	"github.com/google/wire"
)

// ServiceSet 是所有 Service 构造函数的集合
var ServiceSet = wire.NewSet(
	service.NewCaptchaService,
	service.NewUserService,
)
