server:
  name: "gin-app"
  host: "127.0.0.1"
  port: 8088
  mode: "debug"  # debug、release、test
  version: "1.0.0"
  env: "dev"  # dev、test、prod

database:
  driver: "mysql"
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123456"
  dbname: "mydb"
  charset: "utf8mb4"
  prefix: "ev_"

redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0

# 日志配置
log:
  level: "info"              # debug, info, warn, error, fatal
  encoding: "console"        # json, console
  development: false         # 是否为开发模式
  enable_console: true       # 是否输出到控制台
  enable_file: true          # 是否输出到文件

# 文件配置
file:
  dir: "logs"              # 日志目录
  filename: "app"          # 文件名前缀
  max_size: 100            # 单个文件最大MB
  max_age: 30              # 保留天数
  max_backups: 50          # 最大备份文件数
  compress: true           # 是否压缩
  local_time: true         # 是否使用本地时间
  daily_rotate: false       # 日志是否保存一个问题
  time_format: "2006-01-02" # 时间格式

# 验证码
captcha:
  height: 60
  width: 200
  noiseCount: 0
  showLineOptions: 2
  length: 4
  source: "1234567890qwertyuioplkjhgfdsazxcvbnm"


